FROM python:3.11-slim
WORKDIR /sam
COPY requirements.txt .

RUN pip install --upgrade pip \
    && pip install -r requirements.txt

COPY ./app ./app

COPY .env .

ENV PYTHONPATH="/sam"

WORKDIR /sam/app

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]